databases:
  - name: postgres
    databaseName: roomiconnect_production
    user: postgres

services:
  - type: web
    name: postgres
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: postgres
        fromDatabase:
          name: postgres
          property: connectionString
      - key: postgres
        sync: false